# -*- coding: utf-8 -*-
"""06md.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LExBqs4CGfJmGu2D_g_nZqOveD4-476I

# Loop with range

mencetak dengan range angka tertentu
"""

a = int(input('Silahkan masukan angka awal = '))
b = int(input('Silahkan masukan angka akhir = '))
for x in range (a, b+1):
  print(x)

