# -*- coding: utf-8 -*-
"""07md.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UYggS4Age3ss36V6e3qU2MkYEFB-rVbB
"""

start, end = 1, 100
 
# iterating each number in list
for num in range(start, end + 1):
     
    # checking condition
    if num % 2 != 0:
        print(num, end = " ")

